apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nasfaq-web
  namespace: nasfaq
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - holo.nasfaq.biz
      secretName: holo-nasfaq-biz-tls
  rules:
    - host: holo.nasfaq.biz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-web
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-client
                port:
                  name: http
